[project]
name = "text-mud"
version = "0.2.18"
description = "A text-based MUD game"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-cloud-texttospeech>=2.36.0",
    "google-generativeai>=0.8.0",
    "pygame>=2.6.1",
    "rich>=13.7.0",
]

[tool.pytest.ini_options]
pythonpath = ["src", "."]

[dependency-groups]
dev = [
    "mypy>=2.1.0",
]
